# Generated by Django 4.0 on 2022-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=500)),
                ('Group', models.CharField(default='Normal', max_length=15)),
                ('type', models.CharField(default='Normal', max_length=15)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='not sent', max_length=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='communication')),
                ('reason', models.CharField(blank=True, max_length=25, null=True)),
                ('email_sent_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
