# Generated by Django 4.0 on 2022-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='Group',
        ),
        migrations.AddField(
            model_name='email',
            name='group',
            field=models.CharField(default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(default='normal', max_length=15),
        ),
    ]
