# Generated by Django 4.0 on 2022-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_email_group_email_group_alter_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='group',
            field=models.CharField(default='normal', max_length=25),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(default='normal', max_length=25),
        ),
    ]
