# Generated by Django 4.0 on 2022-01-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customAuth', '0001_initial'),
        ('tenant', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_group_bulk', models.CharField(max_length=50)),
                ('is_invoice', models.BooleanField(default=True)),
                ('invoice_duration', models.CharField(default='once', max_length=25)),
                ('status', models.CharField(default='not paid', max_length=25)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('amount_sorted', models.IntegerField(default=0)),
                ('communication', models.CharField(default='None', max_length=25)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('late_fee', models.BooleanField(default=False)),
                ('deadline', models.CharField(default='yes', max_length=10)),
                ('late_fee_category', models.CharField(blank=True, default='generic', max_length=10, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('late_fee_type', models.CharField(blank=True, max_length=30, null=True)),
                ('late_fee_grace', models.IntegerField(blank=True, null=True)),
                ('late_fee_date', models.DateField(blank=True, null=True)),
                ('late_fee_max', models.IntegerField(blank=True, default=0, null=True)),
                ('late_fee_amount', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='user', max_length=10)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_added_by', to='customAuth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_sorted', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_removed', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_added_by', to='customAuth.user')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.lease')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_receipt', models.BooleanField(default=True)),
                ('is_prepayment', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('ref_no', models.CharField(blank=True, max_length=45, null=True)),
                ('paid_through', models.CharField(default='cash', max_length=25)),
                ('communication', models.CharField(default='None', max_length=25)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('created_time', models.TimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='user', max_length=10)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_added_by', to='customAuth.user')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoice')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.lease')),
                ('receipt_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_statements', to='finance.statement')),
            ],
        ),
        migrations.CreateModel(
            name='Late_fee_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('duration', models.CharField(default='once', max_length=50)),
                ('created_for', models.CharField(default='everyone', max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_added_by', to='customAuth.user')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_statements', to='finance.statement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.lease'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(blank=True, max_length=40, null=True)),
                ('expense_name', models.CharField(blank=True, max_length=40, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_for', models.CharField(default='building', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='not paid', max_length=10)),
                ('paid_through', models.CharField(default='cash', max_length=10)),
                ('paid_through_name', models.CharField(blank=True, max_length=45, null=True)),
                ('paid_through_number', models.IntegerField(blank=True, null=True)),
                ('paid_through_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_added_by', to='customAuth.user')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customAuth.payee')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('category', models.CharField(max_length=35)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('notify', models.CharField(blank=True, default='none', max_length=35, null=True)),
                ('duration', models.CharField(blank=True, max_length=35, null=True)),
                ('once_date', models.DateField(blank=True, null=True)),
                ('week_date', models.CharField(blank=True, max_length=15, null=True)),
                ('month_date', models.IntegerField(blank=True, null=True)),
                ('year_date', models.CharField(blank=True, max_length=15, null=True)),
                ('year_day', models.IntegerField(blank=True, null=True)),
                ('year_month', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.CharField(blank=True, default='none', max_length=35, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges_added_by', to='customAuth.user')),
            ],
        ),
    ]
