# Generated by Django 4.0 on 2022-02-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='solution_invoice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
