# Generated by Django 4.0 on 2022-02-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('finance', '0002_receipt_solution_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='data_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenance'),
        ),
        migrations.AddField(
            model_name='expense',
            name='data_type',
            field=models.CharField(default='normal', max_length=15),
        ),
    ]
