# Generated by Django 4.0 on 2022-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_data_id_expense_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(blank=True, default='operating expenses', max_length=40, null=True),
        ),
    ]
