# Generated by Django 4.0 on 2022-02-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='paid_through_name',
            new_name='ref_no',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid_through_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid_through_reference',
        ),
    ]
