# Generated by Django 4.0 on 2022-02-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('finance', '0005_rename_paid_through_name_expense_ref_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
    ]
