# Generated by Django 4.0 on 2022-02-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_alter_payee_options'),
        ('finance', '0006_alter_expense_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customAuth.payee'),
            preserve_default=False,
        ),
    ]
