# Generated by Django 4.0 on 2022-02-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_data_id_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_for',
            field=models.CharField(default='building', max_length=25),
        ),
    ]
