# Generated by Django 4.0 on 2022-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_expense_created_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_through',
            field=models.CharField(default='cash', max_length=25),
        ),
    ]
