# Generated by Django 4.0 on 2022-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_invoice_cancelled_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default='invoice', max_length=25),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
