# Generated by Django 4.0 on 2022-02-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0005_alter_payee_phone_number'),
        ('finance', '0015_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_options',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_option_added_by', to='customAuth.user'),
        ),
        migrations.AddField(
            model_name='payment_options',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
