# Generated by Django 4.0 on 2022-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_charges_deadline_charges_late_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='late_fee_amount',
            field=models.IntegerField(default=0),
        ),
    ]
