# Generated by Django 4.0 on 2022-02-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_charges_late_fee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='late_fee_date',
        ),
    ]
