# Generated by Django 4.0 on 2022-02-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_remove_charges_late_fee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='late_fee_status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
