# Generated by Django 4.0 on 2022-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_invoice_late_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_late_fee',
            field=models.IntegerField(default=0),
        ),
    ]
