# Generated by Django 4.0 on 2022-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_charges_amount_alter_charges_late_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
