# Generated by Django 4.0 on 2022-02-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0008_user_is_employee_alter_user_is_staff'),
        ('finance', '0024_alter_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customAuth.payee'),
        ),
    ]
