# Generated by Django 4.0 on 2022-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_expense_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(default='not paid', max_length=10),
        ),
    ]
