# Generated by Django 4.0 on 2022-02-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(null=True, upload_to='expense'),
        ),
    ]
