# Generated by Django 4.0 on 2022-02-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_expense_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='document',
            new_name='receipt',
        ),
    ]
