# Generated by Django 4.0 on 2022-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_rename_document_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(null=True, upload_to='expense'),
        ),
    ]
