# Generated by Django 4.0 on 2022-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_alter_charges_amount_alter_charges_late_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charges',
            name='late_fee_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='late_fee_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='amount_removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='amount_sorted',
            field=models.IntegerField(default=0),
        ),
    ]
