# Generated by Django 4.0 on 2022-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_alter_charges_amount_alter_charges_late_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_group',
            field=models.CharField(default='expense', max_length=50),
        ),
    ]
