# Generated by Django 4.0 on 2022-02-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_expense_expense_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(default='test expense', max_length=75),
            preserve_default=False,
        ),
    ]
