# Generated by Django 4.0 on 2022-03-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_alter_expense_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='category',
            field=models.CharField(default='custom', max_length=35),
        ),
    ]
