# Generated by Django 4.0 on 2022-03-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_property_property_rent_amount_and_more'),
        ('finance', '0039_alter_charges_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
    ]
