# Generated by Django 4.0 on 2022-02-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
