# Generated by Django 4.0 on 2022-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(default='profile/no_profile.jpg', upload_to='profile'),
        ),
    ]
