# Generated by Django 4.0 on 2022-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='end_lease_notice',
            field=models.CharField(default='not sent', max_length=15),
        ),
    ]
