# Generated by Django 4.0 on 2022-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_tenant_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_group',
            field=models.CharField(default='rent', max_length=35),
        ),
        migrations.AddField(
            model_name='lease',
            name='purchase_price',
            field=models.IntegerField(default=0),
        ),
    ]
