# Generated by Django 4.0 on 2022-02-27 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_lease_paid_through_lease_ref_no_alter_lease_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
