# Generated by Django 4.0 on 2022-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_alter_lease_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='is_paid',
            field=models.BooleanField(default='yes', max_length=5),
        ),
    ]
