# Generated by Django 4.0 on 2022-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_alter_lease_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='is_paid',
            field=models.CharField(default='yes', max_length=5),
        ),
    ]
