# Generated by Django 4.0 on 2022-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='payee_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='category',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='individual', max_length=15),
        ),
    ]
