# Generated by Django 4.0 on 2022-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_payee_payee_category_alter_payee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
