# Generated by Django 4.0 on 2022-01-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customAuth', '0001_initial'),
        ('tenant', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(default='normal', max_length=35)),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('category', models.CharField(max_length=35)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_on', models.DateField(blank=True, null=True)),
                ('solved_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='not started', max_length=35)),
                ('urgency', models.CharField(default='not urgent', max_length=20)),
                ('opened', models.BooleanField(default=False)),
                ('added_by_category', models.CharField(default='admin', max_length=35)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_added_by', to='customAuth.user')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
            options={
                'ordering': ['-reported_on'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(null=True, upload_to='maintenane')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_added_by', to='customAuth.user')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(default='materials', max_length=35)),
                ('cost_name', models.CharField(blank=True, max_length=35, null=True)),
                ('cost_number', models.IntegerField(default=1)),
                ('cost_description', models.TextField(blank=True, null=True)),
                ('cost_total', models.IntegerField()),
                ('paid', models.CharField(default='not paid', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(default='us', max_length=10)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_added_by', to='customAuth.user')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenance')),
            ],
        ),
    ]
