# Generated by Django 4.0 on 2022-02-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_alter_payee_options'),
        ('maintenance', '0002_cost_paid_through_cost_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='payee',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='customAuth.payee'),
            preserve_default=False,
        ),
    ]
