# Generated by Django 4.0 on 2022-02-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0005_alter_payee_phone_number'),
        ('maintenance', '0004_remove_maintenance_payee_cost_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customAuth.payee'),
        ),
    ]
