# Generated by Django 4.0 on 2022-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='size',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
