# Generated by Django 4.0 on 2022-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_unit_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
