# Generated by Django 4.0 on 2022-02-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0008_user_is_employee_alter_user_is_staff'),
        ('property', '0004_alter_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='random_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Property_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(null=True, upload_to='property')),
                ('random_value', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.CharField(blank=True, default='none', max_length=35, null=True)),
                ('name', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_document_added_by', to='customAuth.user')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_document_property', to='property.property')),
            ],
        ),
    ]
