# Generated by Django 4.0 on 2022-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_random_value_property_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_documents',
            name='category',
            field=models.CharField(default='document', max_length=50),
        ),
    ]
