# Generated by Django 4.0 on 2022-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_utility_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility_bills',
            name='duration',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='utility_bills',
            name='month_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility_bills',
            name='once_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility_bills',
            name='week_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utility_bills',
            name='year_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utility_bills',
            name='year_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility_bills',
            name='year_month',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
