# Generated by Django 4.0 on 2022-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_ownership_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility_bills',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
