# Generated by Django 4.0 on 2022-03-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_property_occupancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_rent_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_rent_category',
            field=models.CharField(default='custom', max_length=35),
        ),
        migrations.AddField(
            model_name='property',
            name='property_rent_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_rent_duration',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_rent_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
