# Generated by Django 4.0 on 2022-02-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_remove_charges_late_fee_date'),
        ('notifications', '0003_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.statement'),
        ),
    ]
