# Generated by Django 4.0 on 2022-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='from_group',
            field=models.CharField(default='system', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_group',
            field=models.CharField(default='tenant', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
