# Generated by Django 4.0 on 2022-02-28 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_expense_expense_group'),
        ('notifications', '0005_remove_notification_to_user_notification_from_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.expense'),
        ),
    ]
